# Generated by Django 3.1.3 on 2020-11-23 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='page',
            new_name='collection',
        ),
    ]
