# Generated by Django 3.1.3 on 2020-11-23 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_auto_20201123_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_page_rel', to='journal.journalcollection'),
        ),
    ]
