# Generated by Django 4.0.1 on 2022-02-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_event_number_of_recurrences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='date',
        ),
    ]
